#  ##   ##   ####    ##   ##   #####              ####   ####      #####   ##   ##  #####             ##   ##   #####   ######            ######   #######    ##     ##   ## #
#  ##   ##    ##     ###  ##  ##   ##            ##  ##   ##      ##   ##  ##   ##   ## ##            ### ###  ##   ##   ##  ##           # ## #    ##   #   ####    ### ### #
#  ##   ##    ##     #### ##  #                 ##        ##      ##   ##  ##   ##   ##  ##           #######  #         ##  ##             ##      ## #    ##  ##   ####### #
#  ## # ##    ##     ## ####   #####            ##        ##      ##   ##  ##   ##   ##  ##           #######   #####    #####              ##      ####    ##  ##   ####### #
#  #######    ##     ##  ###       ##           ##        ##   #  ##   ##  ##   ##   ##  ##           ## # ##       ##   ##                 ##      ## #    ######   ## # ## #
#  ### ###    ##     ##   ##  ##   ##            ##  ##   ##  ##  ##   ##  ##   ##   ## ##            ##   ##  ##   ##   ##                 ##      ##   #  ##  ##   ##   ## #
#  ##   ##   ####    ##   ##   #####              ####   #######   #####    #####   #####             ##   ##   #####   ####               ####    #######  ##  ##   ##   ## #
--- 
- name: "Cloud MSP Initial set"
  hosts: Ubuntu
  become: yes
  gather_facts: no

  tasks:
     ###############################
     ###### STEP 0. 백업     
    - name: "STEP 0-0. Config File Backup"
      command: date +"%Y-%m-%d_%H-%M-%S"
      register: ldate

    - name: "STEP 0-1. Make a Backup Directory "
      file:
        path: "/root/winsBackup_{{ ldate.stdout }}"
        state: directory

    - name: "STEP 0-2. /etc/localtime Backup"
      copy:
        src: /etc/localtime
        dest: "/root/winsBackup_{{ ldate.stdout }}/localtime"

    - name: "STEP 0-3. /etc/profile Backup"
      copy:
        src: /etc/profile
        dest: "/root/winsBackup_{{ ldate.stdout }}/profile"

    - name: "STEP 0-4. /etc/ssh/sshd_config Backup"
      copy:
        src: /etc/ssh/sshd_config
        dest: "/root/winsBackup_{{ ldate.stdout }}/sshd_config"

    - name: "STEP 0-5. /etc/chrony/chrony.conf Backup"
      copy:
        src: /etc/chrony/chrony.conf
        dest: "/root/winsBackup_{{ ldate.stdout }}/chrony.conf"


     ###############################
     ###### STEP 1. 타임존 변경
    - name: "STEP 1. UTC to KST Converter"
      file:
        src: /usr/share/zoneinfo/Asia/Seoul
        dest: /etc/localtime
        owner: root
        group: root
        state: link


     ###############################
     ###### STEP 2. 히스토리 시간 포맷 설정        
    - name: "STEP 2. History Time Logging"
      lineinfile:
        path: /etc/profile
        line: HISTTIMEFORMAT=\"[%Y-%m-%d_%H:%M:%S]


     ###############################
     ###### STEP 3. root 로그인 제한
    - name: "STEP 3-1. SSH root login: Block to access root ssh directly"
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PermitRootLogin prohibit-password'
        replace: 'PermitRootLogin no'

    - name: "STEP 3-2. SSH Password Login: Allow to login with password"        
      replace:
        path: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication no'
        replace: 'PasswordAuthentication yes'  

    - name: "STEP 3-3. SSH Service : restart sshd"
      service:
        name: sshd
        state: restarted


     ###############################
     ###### STEP 4. 계정 패스워드 변경
    - name: "STEP 4-1. Set root password"
      user:
        name: root
        password: "{{ 'Sniper13@$' | password_hash('sha512') }}"

    - name: "STEP 4-2. Set password for ubuntu"
      user:
        name: ubuntu
        password: "{{ 'Sniper13@$' | password_hash('sha512') }}"

    - name: "STEP 4-3. Display the result"
      debug:
        msg: "Password is set."
    

     ###############################
     ###### STEP 5. 네트워크 기본 툴 패키지 설치
    - name: "STEP 5. Network Tool Install"
      apt:
        name:
          - iputils-*
          - net-tools
          - tcpdump
        state: present


     ###############################
     ###### STEP 6. NTP 설정
    - name: "STEP 6-1. NTP Client Configuration: Remove origin NTP server"
      lineinfile:
        path: /etc/chrony/chrony.conf
        state: absent
        regexp: "^pool"

    - name: "STEP 6-2. NTP Client Configuration: Add a NTP Korea Server"
      lineinfile:
        path: /etc/chrony/chrony.conf
        insertafter: '# See http://www.pool.ntp.org/join.html for more information.'
        line: 'server time.bora.net iburst'

    - name: "STEP 6-3. NTP Client Configuration: restart chrony"
      service:
        name: chrony
        state: restarted


     ###############################
     ###### 모든 작업 완료
    - name: "TASK IS Done"
      debug:
        msg: "ALL OF TASK IS Done" 
