#  ##   ##   ####    ##   ##   #####              ####   ####      #####   ##   ##  #####             ##   ##   #####   ######            ######   #######    ##     ##   ## #
#  ##   ##    ##     ###  ##  ##   ##            ##  ##   ##      ##   ##  ##   ##   ## ##            ### ###  ##   ##   ##  ##           # ## #    ##   #   ####    ### ### #
#  ##   ##    ##     #### ##  #                 ##        ##      ##   ##  ##   ##   ##  ##           #######  #         ##  ##             ##      ## #    ##  ##   ####### #
#  ## # ##    ##     ## ####   #####            ##        ##      ##   ##  ##   ##   ##  ##           #######   #####    #####              ##      ####    ##  ##   ####### #
#  #######    ##     ##  ###       ##           ##        ##   #  ##   ##  ##   ##   ##  ##           ## # ##       ##   ##                 ##      ## #    ######   ## # ## #
#  ### ###    ##     ##   ##  ##   ##            ##  ##   ##  ##  ##   ##  ##   ##   ## ##            ##   ##  ##   ##   ##                 ##      ##   #  ##  ##   ##   ## #
#  ##   ##   ####    ##   ##   #####              ####   #######   #####    #####   #####             ##   ##   #####   ####               ####    #######  ##  ##   ##   ## #



- name: "Cloud MSP Initial set"
  hosts: all #ubuntu
  become: yes
  gather_facts: no

  tasks:
     ###############################
     ###### STEP 0. 백업
     
    - name: "STEP 0. Config File Backup"
      command: date +"%Y-%m-%d_%H-%M-%S"
      register: ldate

    - name: "STEP 0-1. Make a Backup Directory "
      file:
        path: "/root/winsBackup_{{ ldate.stdout }}"
        state: directory

    - name: "STEP 0-2. /etc/localtime Backup"
      copy:
        src: /etc/localtime
        dest: "/root/winsBackup_{{ ldate.stdout }}/localtime"

    - name: "STEP 0-3. /etc/profile Backup"
      copy:
        src: /etc/profile
        dest: "/root/winsBackup_{{ ldate.stdout }}/profile"

    - name: "STEP 0-4. /etc/ssh/sshd_config Backup"
      copy:
        src: /etc/ssh/sshd_config
        dest: "/root/winsBackup_{{ ldate.stdout }}/sshd_config"

    - name: "STEP 0-5. /etc/chrony/chrony.conf Backup"
      copy:
        src: /etc/chrony/chrony.conf # ubuntu 22.04
        dest: "/root/winsBackup_{{ ldate.stdout }}/chrony.conf"

     ###############################

     ###############################
     ###### STEP 1. 타임존 변경
 
    - name: "STEP 1. UTC to KST Converter"
      file:
        src: /usr/share/zoneinfo/Asia/Seoul
        dest: /etc/localtime
        owner: root
        group: root
        state: link

     ###############################



     ###############################
     ###### STEP 2. 타임존 변경        
    - name: "2. History Time Logging"
      lineinfile:
        path: /etc/profile
        line: HISTTIMEFORMAT=\"[%Y-%m-%d_%H:%M:%S]

     ###############################


     ###############################
     ###### STEP 3. root 로그인 제한

    - name: "3-1. SSH root login: Block to access root ssh directly"
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PermitRootLogin prohibit-password'
        replace: 'PermitRootLogin no'

    - name: "3-2. SSH Password Login: Allow to login with password"        
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication no'
        replace: 'PasswordAuthentication yes'

    - name: "3-3. SSH Password Login: Use Authentication based on GSSAPI"
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#GSSAPIAuthentication no'
        replace: 'GSSAPIAuthentication yes'

     ###############################


     ###############################
     ###### STEP 4. 계정 패스워드 변경

    - name: STEP 4-1. Check if password is already set for root
      command: "grep -E '^root:[*!]' /etc/shadow"  # root 계정만 있음
      register: grep_result
      changed_when: false  # 명령이 실행되면 항상 변경으로 표시되지 않도록 함

    - name: STEP 4-2. Set password for root
      shell: "echo 'Sniper13@$' | passwd --stdin root > /dev/null"
      when: grep_result.rc != 0  # 이미 비밀번호가 설정되어 있으면 변경하지 않음

    - name: STEP 4-3. Display the result
      debug:
        msg: "Password for root is set."
      when: grep_result.rc == 0  # 이미 비밀번호가 설정되어 있으면 출력하지 않음      


     ###############################






     ###############################             

     ###############################
     ###### STEP 8. 네트워크 기본 툴 패키지 설치
     
    - name: "STEP 8-1. Network Tool Install" # dnf로 패키지 설치
      apt:
        name: iputils, net-tools, tcpdump
        state: latest # 최신버전이 아니면 업데이트도 진행
        # state: present # 설치 확인만     
      
    - name: "STEP 8-2. Check if the RPM is installed"
      command: "rpm -q iputils,net-tools,tcpdump"
      register: rpm_check_result
      ignore_errors: true  # RPM이 설치되어 있지 않으면 오류를 무시

    - name: "STEP 8-3. Display the result"
      debug:
        msg: "The RPM is {{ 'installed' if rpm_check_result.rc == 0 else 'not installed' }}" 

     ###############################


     ###############################
     ###### STEP 9. NTP 설정

    - name: "STEP 9-1. NTP Client Configuration -1" # 기본 ntp 설정 주석
      replace:
        path: /etc/chrony.conf
        regexp: 'pool 2.rocky.pool.ntp.org iburst'
        replace: '#pool 2.rocky.pool.ntp.org iburst'

    - name: "STEP 9-2. NTP Client Configuration -2" # time.bora.net 추가
      lineinfile:
        path: /etc/chrony.conf
        insertafter: '#pool 2.rocky.pool.ntp.org iburst'
        line: "server time.bora.net iburst"
